# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller spec for the desktop bundles: Windows and macOS (Apple silicon).

Windows: a onedir tree, ``pyALDIC.exe`` plus a console twin, which
tools/build_exe.py zips (the portable download) and wraps with Inno Setup
(the installer). macOS: the same tree wrapped as ``pyALDIC.app``, which the
build script puts on a .dmg. Neither needs Python or administrator rights.

Build with ``python tools/build_exe.py`` (which pins the output paths away from
``dist/``, the directory the PyPI workflow publishes from).

The two things most likely to go wrong here are silent, so both are asserted
at build time rather than discovered by a user:

* the ``al_dic/`` prefix on every ``datas`` destination. A frozen package's
  ``__file__`` is ``sys._MEIPASS/al_dic/<subpkg>/__init__.py``, so the data
  directories the code resolves with ``Path(__file__).parent / ...`` only line
  up if the destination mirrors the package path. Get it wrong and the app
  still starts -- with seven of eight languages gone, blank spin-box arrows
  and no window icon.
* the presence of the compiled ``.qm`` catalogs, which are build products.
"""

import glob
import os
import sys

from PyInstaller.utils.hooks import copy_metadata

# --------------------------------------------------------------------------
# Preconditions
# --------------------------------------------------------------------------
SRC = os.path.join(SPECPATH, os.pardir, "src")
PKG = os.path.join(SRC, "al_dic")
IS_MAC = sys.platform == "darwin"
IS_WINDOWS = sys.platform == "win32"

# 'en' is absent by design: LanguageManager short-circuits it to the source
# strings rather than loading a catalog.
LOCALES = ("de", "es", "fr", "ja", "ko", "zh_CN", "zh_TW")
for _lc in LOCALES:
    _qm = os.path.join(PKG, "i18n", "compiled", f"al_dic_{_lc}.qm")
    assert os.path.isfile(_qm), (
        f"missing translation catalog {_qm}\n"
        "run: python tools/i18n.py compile"
    )

_arrows = glob.glob(os.path.join(PKG, "gui", "arrows", "*.svg"))
assert len(_arrows) == 4, f"expected 4 spin-box arrow SVGs, found {len(_arrows)}"

for _ic in ("pyALDIC.ico", "pyALDIC-256.png", "pyALDIC.svg", "pyALDIC.icns"):
    assert os.path.isfile(os.path.join(PKG, "gui", "assets", "icon", _ic)), _ic

# The .icns was rendered from pyALDIC.svg at 1024 px (16 to 512@2x inside).
ICON = os.path.join(PKG, "gui", "assets", "icon",
                    "pyALDIC.icns" if IS_MAC else "pyALDIC.ico")

# --------------------------------------------------------------------------
# Version resource (Explorer properties / SmartScreen reputation)
# --------------------------------------------------------------------------
_ver_ns = {}
with open(os.path.join(PKG, "__init__.py"), encoding="utf-8") as _f:
    for _line in _f:
        if _line.startswith("__version__"):
            exec(_line, _ver_ns)
            break
VERSION = _ver_ns["__version__"]
_v = tuple(int(p) for p in VERSION.split(".")[:3]) + (0,)

# A Windows PE resource; macOS reads its version from Info.plist instead.
VERSION_FILE = os.path.join(SPECPATH, "version_info.txt") if IS_WINDOWS else None
_VERSION_INFO = f"""# Generated by pyaldic.spec -- do not edit, do not commit.
VSVersionInfo(
  ffi=FixedFileInfo(filevers={_v}, prodvers={_v}, mask=0x3f, flags=0x0,
                    OS=0x40004, fileType=0x1, subtype=0x0, date=(0, 0)),
  kids=[
    StringFileInfo([StringTable('040904B0', [
        StringStruct('CompanyName', 'Zixiang (Zach) Tong'),
        StringStruct('FileDescription', 'pyALDIC - Augmented Lagrangian Digital Image Correlation'),
        StringStruct('FileVersion', '{VERSION}'),
        StringStruct('InternalName', 'pyALDIC'),
        StringStruct('LegalCopyright', 'BSD-3-Clause'),
        StringStruct('OriginalFilename', 'pyALDIC.exe'),
        StringStruct('ProductName', 'pyALDIC'),
        StringStruct('ProductVersion', '{VERSION}')])]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])])
  ]
)
"""
if VERSION_FILE:
    with open(VERSION_FILE, "w", encoding="utf-8") as _f:
        _f.write(_VERSION_INFO)

# --------------------------------------------------------------------------
# Bundle contents
# --------------------------------------------------------------------------
datas = [
    # The 'al_dic/' destination prefix is load-bearing -- see the module
    # docstring. Each of these is resolved at runtime with
    # Path(__file__).parent, in i18n/__init__.py, gui/theme.py and gui/icons.py.
    (os.path.join(PKG, "i18n", "compiled", "*.qm"), "al_dic/i18n/compiled"),
    (os.path.join(PKG, "gui", "arrows", "*.svg"), "al_dic/gui/arrows"),
    (os.path.join(PKG, "gui", "assets", "icon", "*"), "al_dic/gui/assets/icon"),
]

# imageio/__init__.py calls importlib.metadata.version("imageio") at import
# time, which raises PackageNotFoundError unless the .dist-info comes along.
datas += copy_metadata("imageio")

hiddenimports = [
    # Imported behind try/except in gui/icons.py. Losing it does not raise --
    # every toolbar icon silently becomes an empty QIcon.
    "PySide6.QtSvg",

    # Numba picks a threading backend by trying these in order, with
    # function-level imports the module graph cannot see. tbbpool is
    # deliberately absent: TBB is not a dependency of this project, the
    # environment does not provide tbb12.dll, and listing it made PyInstaller
    # satisfy the dependency from Anaconda's base environment -- which then won
    # the layer selection, so the bundle ran on a thread pool the developers
    # never tested and no user could have. omp (vcomp140.dll, bundled above) is
    # the intended layer on Windows; workqueue is the fallback, and on macOS
    # (whose wheels ship no OpenMP pool) the layer itself. omppool is appended
    # below for Windows only.
    "numba.np.ufunc.workqueue",
    "numba.np.ufunc._internal",
    "numba.np.ufunc._num_threads",

    # Named only as the string "Agg" in export/colorbar.py.
    "matplotlib.backends.backend_agg",
    # Resolved through matplotlib.use("QtAgg") in gui/widgets/mpl_chart.py.
    "matplotlib.backends.backend_qtagg",

    # GIF export resolves the "GIF" plugin string to this at runtime.
    "imageio.plugins.pillow",
    "PIL.Image",
    "PIL.GifImagePlugin",
]
if IS_WINDOWS:
    hiddenimports.append("numba.np.ufunc.omppool")

binaries = []

# OpenCV's FFmpeg backend. hook-cv2 collects cv2's DLLs, but the filename
# embeds the OpenCV version (4.13 -> ...ffmpeg4130_64.dll, 5.0 ->
# ...ffmpeg500_64.dll), so glob rather than hardcode. Without it every video
# export fails: both the mp4v path and the XVID/.avi fallback refuse to open.
try:
    import cv2 as _cv2

    for _dll in glob.glob(
        os.path.join(os.path.dirname(_cv2.__file__), "opencv_videoio_ffmpeg*.dll")
    ):
        binaries.append((_dll, "cv2"))
except ImportError:  # pragma: no cover
    pass

# The OpenMP runtime backing numba's 'omp' threading layer. It resolves from
# System32 (the VC++ redistributable), which PyInstaller excludes from
# collection by design -- so on a machine without the redistributable,
# omppool fails to import and numba drops to 'workqueue' without saying so.
# App-local deployment of this DLL is permitted by the redistributable licence.
_vcomp = os.path.join(
    os.environ.get("SystemRoot", r"C:\Windows"), "System32", "vcomp140.dll"
)
if os.path.isfile(_vcomp):
    binaries.append((_vcomp, "."))

excludes = [
    # --- Qt modules the application does not import ----------------------
    # Kept: QtCore, QtGui, QtWidgets, QtSvg. These are insurance rather than a
    # saving: PyInstaller's Qt hooks are per-module, so on a correct build the
    # heavy ones are already absent. They stop a stray collect_all('PySide6')
    # from doubling the bundle.
    "PySide6.Qt3DAnimation", "PySide6.Qt3DCore", "PySide6.Qt3DExtras",
    "PySide6.Qt3DInput", "PySide6.Qt3DLogic", "PySide6.Qt3DRender",
    "PySide6.QtAxContainer", "PySide6.QtBluetooth", "PySide6.QtCharts",
    "PySide6.QtConcurrent", "PySide6.QtDataVisualization", "PySide6.QtDBus",
    "PySide6.QtDesigner", "PySide6.QtGraphs", "PySide6.QtGraphsWidgets",
    "PySide6.QtHelp", "PySide6.QtHttpServer", "PySide6.QtLocation",
    "PySide6.QtMultimedia", "PySide6.QtMultimediaWidgets",
    "PySide6.QtNetworkAuth", "PySide6.QtNfc", "PySide6.QtOpenGL",
    "PySide6.QtOpenGLWidgets", "PySide6.QtPdf", "PySide6.QtPdfWidgets",
    "PySide6.QtPositioning", "PySide6.QtQml", "PySide6.QtQuick",
    "PySide6.QtQuick3D", "PySide6.QtQuickControls2", "PySide6.QtQuickTest",
    "PySide6.QtQuickWidgets", "PySide6.QtRemoteObjects", "PySide6.QtScxml",
    "PySide6.QtSensors", "PySide6.QtSerialBus", "PySide6.QtSerialPort",
    "PySide6.QtSpatialAudio", "PySide6.QtSql", "PySide6.QtStateMachine",
    "PySide6.QtSvgWidgets", "PySide6.QtTest", "PySide6.QtTextToSpeech",
    "PySide6.QtUiTools", "PySide6.QtWebChannel", "PySide6.QtWebEngineCore",
    "PySide6.QtWebEngineQuick", "PySide6.QtWebEngineWidgets",
    "PySide6.QtWebSockets", "PySide6.QtWebView", "PySide6.QtXml",

    # QtNetwork and QtPrintSupport are deliberately NOT excluded: neither is
    # imported, so neither is collected, and excluding a module Qt might pull
    # internally trades a guaranteed crash for a saving of zero bytes.

    # Rival Qt bindings must never co-exist in one bundle.
    "PyQt5", "PyQt6", "PySide2", "shiboken2",

    # Imported nowhere in src/, tests/, tools/ or examples/, and no longer a
    # dependency (dropped from pyproject.toml in 0.9.0). Excluding it keeps a
    # stray import in a build environment that happens to have it from
    # dragging in 25 MB plus scikit-image's seventeen collect-everything hooks.
    "skimage",

    # imageio plugins that are unreachable: only "GIF" (-> pillow) is used.
    # imageio_ffmpeg would otherwise add a ~87 MB ffmpeg.exe.
    "imageio_ffmpeg", "imageio.plugins.ffmpeg", "imageio.plugins.pyav",
    "imageio.plugins.freeimage", "imageio.plugins.gdal",
    "imageio.plugins.rawpy", "imageio.plugins.simpleitk",
    "imageio.plugins.dicom", "imageio.plugins.fits",

    # backend_qtagg is NOT excluded: the analysis tab embeds a live figure
    # (gui/widgets/mpl_chart.py), and screen and export deliberately share one
    # rendering path. Excluding it produced a bundle whose chart tab failed
    # silently, which is why self_test checks that it imports and renders.
    "matplotlib.backends.backend_qtcairo",
    "matplotlib.backends.backend_webagg",
    "matplotlib.backends.backend_tkagg",

    # QtNetwork: nothing links Qt6Network.dll except QtNetwork.pyd itself
    # (verified against the PE import tables of Qt6Core/Gui/Widgets/Svg), and
    # it arrives only because PySide6's hook offers it. Qt loads OpenSSL
    # lazily for QSslSocket, so carrying it means carrying a TLS stack for a
    # module the application never imports.
    "PySide6.QtNetwork",

    # TLS. Nothing under src/al_dic imports ssl, urllib, requests or http --
    # this is a desktop application that reads images off a disk. The module
    # graph pulls `ssl` in through the standard library, and with it an
    # OpenSSL pair whose filenames differ between Python builds
    # (libssl-3-x64.dll from conda, libssl-3.dll from python.org), so whether
    # a build succeeds ends up depending on which Python built it. Shipping a
    # TLS library that is never used and never patched is worse than not
    # shipping one.
    "ssl", "_ssl",

    # _hashlib is OpenSSL's implementation of hashlib's algorithms. The
    # standard library falls back to the built-in _sha1/_sha256/_md5/_blake2
    # modules without it, and this application only ever calls
    # hashlib.sha256 (io/session_serialize.py) and, through Numba,
    # hashlib.sha1. Verified byte-identical digests with and without it.
    # Excluding it removes the last reason to carry libcrypto.
    "_hashlib",

    # Never imported by the application.
    "tkinter", "IPython", "jupyter", "notebook", "pytest", "hypothesis",
    "sphinx", "pandas", "setuptools", "pip",
]

# --------------------------------------------------------------------------
# Ambient-DLL guard
# --------------------------------------------------------------------------
# PyInstaller resolves a binary dependency by searching PATH, so any DLL the
# build machine happens to have can end up in the bundle and shadow the one
# the target machine would have used. That is not hypothetical: it broke the
# first build of this spec outright.
#
# PySide6's Qt6Core.dll is built against the ICU that ships in Windows'
# System32, which exports UNVERSIONED symbols (ucnv_open). A standard ICU
# build -- Anaconda's, for one -- exports VERSIONED symbols (ucnv_open_73) and
# nothing else. Collecting the latter into the bundle root shadowed System32's
# copy, so Qt6Core could not resolve ucnv_open and every PySide6 import died
# with "DLL load failed ... The specified procedure could not be found". The
# application never got a window; nothing was logged; nothing named ICU.
#
# Windows 10 1703 and later always provide System32's ICU, so dropping these
# is safe as well as necessary.
# Must resolve from Windows, never from the bundle.
#
# The Universal CRT (ucrtbase.dll plus the api-ms-win-* forwarders) is an
# operating-system component from Windows 10 onward, kept current by Windows
# Update, and this bundle targets Windows 10 1703 and later. Shipping it is
# only necessary for Windows 7 and 8.1.
#
# Leaving it collectible makes the bundle's contents depend on which unrelated
# toolchain happens to sit on the build machine's PATH: a conda environment
# supplies one copy, and a GitHub Windows runner supplies a different one from
# the bundled Temurin JDK. Neither belongs to pyALDIC, and the difference is
# invisible until it is not. Dropping them makes the build reproducible across
# machines.
AMBIENT_DENY = (
    "icuuc", "icuin", "icudt", "icuio",
    "ucrtbase", "api-ms-win",
)

# Dead weight that decides behaviour if it is allowed to load. numba ships
# tbbpool.pyd inside its package, so PyInstaller collects it as an ordinary
# binary whatever hiddenimports says, and tbbpool.pyd imports tbb12.dll. This
# environment has no tbb12.dll -- `from numba.np.ufunc import tbbpool` raises
# ImportError here -- so PyInstaller satisfied it from Anaconda's base
# installation instead. The bundle then selected 'tbb' as its threading layer:
# a thread pool nobody had tested, that no user of the wheel would ever get.
# Dropping the extension leaves 'omp' (vcomp140.dll, bundled above) with
# 'workqueue' behind it, which is what the source install uses.
DEAD_EXTENSIONS = ("tbbpool", "tbb12")

# Qt libraries that no reachable code loads. Excluding the Python modules is
# not enough: PyInstaller's Qt hook collects the shared libraries anyway, and
# these five drag in Qt6Network, which in turn wants an OpenSSL pair whose
# filenames differ between Python distributions -- libssl-3-x64.dll from
# conda, libssl-3.dll from python.org -- so leaving them in makes a successful
# build depend on which machine ran it.
#
# Verified against the PE import tables of the bundle: Qt6Core imports no other
# Qt library, Qt6Gui imports only Qt6Core, and Qt6Widgets and Qt6Svg import
# only Qt6Gui and Qt6Core. Qt6Network was reached solely from Qt6Pdf, Qt6Qml,
# Qt6Quick and the TUIO touch plugin, none of which this application uses.
#
# Qt6OpenGL and opengl32sw are deliberately kept: opengl32sw is Qt's software
# rasteriser fallback, and lab machines running over remote desktop or in a VM
# are exactly where it earns its 20 MB.
DEAD_QT_LIBS = (
    "qt6network", "qt6pdf", "qt6qml", "qt6quick", "qt6virtualkeyboard",
    "qtuiotouchplugin",
)

# Sourced from outside the environment on purpose: see the vcomp140 note above.
AMBIENT_ALLOW = {"vcomp140.dll"}


def _find_requesters(names, binaries):
    """Map each lowercase DLL name to the collected binaries that import it."""
    try:
        import pefile
    except ImportError:  # pragma: no cover - pefile ships with PyInstaller
        return {}
    found = {}
    for entry in binaries:
        path = str(entry[1] or "")
        if not path.lower().endswith((".dll", ".pyd")):
            continue
        try:
            pe = pefile.PE(path, fast_load=True)
            pe.parse_data_directories(
                directories=[pefile.DIRECTORY_ENTRY[
                    "IMAGE_DIRECTORY_ENTRY_IMPORT"]]
            )
            imports = {e.dll.decode("ascii", "replace").lower()
                       for e in getattr(pe, "DIRECTORY_ENTRY_IMPORT", [])}
            pe.close()
        except Exception:
            continue
        for name in names & imports:
            found.setdefault(name, []).append(os.path.basename(entry[0]))
    return found


def _drop_ambient(binaries):
    """Remove DLLs that must resolve from the OS, and report the rest."""
    kept, dropped = [], []
    for entry in binaries:
        name = os.path.basename(entry[0]).lower()
        unwanted = (
            name.startswith(AMBIENT_DENY)
            or name.startswith(DEAD_EXTENSIONS)
            or name.startswith(DEAD_QT_LIBS)
        )
        (dropped if unwanted else kept).append(entry)
    for entry in dropped:
        print(f"spec: dropping {entry[0]} <- {entry[1]}")

    # Anything else sourced from outside the build environment is the same
    # class of hazard. It has already produced three distinct instances here,
    # each from a different unrelated toolchain that happened to be installed:
    # Anaconda's ICU and libexpat locally, the Temurin JDK's Universal CRT on a
    # GitHub runner, MySQL Server's OpenSSL on the same runner.
    #
    # Refusing outright is the wrong response when the build environment ships
    # its own copy of the same library -- and it usually does, because that is
    # the copy the extension module was linked against. Re-point to it. Only
    # when there is nothing to fall back to is the build genuinely unsafe.
    #
    # sys.base_prefix covers a venv, whose stdlib extension DLLs and their
    # dependencies live in the base installation.
    roots = []
    for base in (sys.prefix, sys.base_prefix):
        for sub in ("", "DLLs", "Library/bin", "Library/mingw-w64/bin",
                    "Library/usr/bin", "Scripts"):
            path = os.path.join(base, *sub.split("/")) if sub else base
            if os.path.isdir(path) and path not in roots:
                roots.append(path)
    normalised_roots = {os.path.normcase(r) for r in
                        (sys.prefix, sys.base_prefix)}

    repaired, strays = [], []
    for index, entry in enumerate(kept):
        src = str(entry[1] or "")
        if not src or os.path.basename(src) in AMBIENT_ALLOW:
            continue
        if any(os.path.normcase(src).startswith(r) for r in normalised_roots):
            continue
        name = os.path.basename(src)
        local = next(
            (os.path.join(r, name) for r in roots
             if os.path.isfile(os.path.join(r, name))),
            None,
        )
        if local is None:
            strays.append((entry[0], src))
        else:
            kept[index] = (entry[0], local) + tuple(entry[2:])
            repaired.append((entry[0], src, local))

    for dest, was, now in repaired:
        print(f"spec: re-pointed {dest}\n"
              f"        away from {was}\n"
              f"        to        {now}")

    if strays and not os.environ.get("PYALDIC_ALLOW_AMBIENT"):
        # Name whatever asked for each stray. Without this the message says a
        # DLL is unaccounted for but not which of six hundred files wanted it,
        # which is the difference between a fix and another build.
        requesters = _find_requesters({os.path.basename(src).lower()
                                       for _, src in strays}, kept)
        listing = "\n".join(
            f"    {dest}  <-  {src}"
            + (f"\n        requested by: "
               + ", ".join(requesters.get(os.path.basename(src).lower(), []))
               if requesters.get(os.path.basename(src).lower()) else "")
            for dest, src in strays
        )
        searched = "\n".join(f"      {r}" for r in roots)
        raise SystemExit(
            "\nspec: refusing to build -- these binaries were resolved from "
            "outside the build\n"
            f"      environment ({sys.prefix}), and it has no copy of its "
            "own:\n"
            f"{listing}\n\n"
            "      A DLL picked up from the build machine's PATH shadows the "
            "one the\n"
            "      target machine would load, and the failure is silent: the "
            "bundle\n"
            "      builds, starts, and loses a feature.\n\n"
            f"      Looked for a local copy in:\n{searched}\n\n"
            "      Set PYALDIC_ALLOW_AMBIENT=1 to override deliberately."
        )
    return kept


a = Analysis(
    [os.path.join(SPECPATH, "pyaldic_launcher.py")],
    pathex=[SRC],
    binaries=binaries,
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[os.path.join(SPECPATH, "rthook_pyaldic.py")],
    excludes=excludes,
    noarchive=False,
    optimize=0,
)

a.binaries = _drop_ambient(a.binaries)

pyz = PYZ(a.pure)

if IS_MAC:
    # One windowed executable: run from Terminal it still has a stdout, which
    # is where CI reads the self-test from, so no console twin is needed.
    # Ad-hoc signed (codesign_identity=None), not notarized: the first launch
    # of a downloaded copy goes through System Settings > Privacy & Security >
    # Open Anyway. argv_emulation stays off -- Qt handles Apple events itself.
    exe = EXE(
        pyz,
        a.scripts,
        [],
        exclude_binaries=True,
        name="pyALDIC",
        debug=False,
        bootloader_ignore_signals=False,
        strip=False,
        upx=False,
        console=False,
        disable_windowed_traceback=False,
        argv_emulation=False,
        target_arch="arm64",
        codesign_identity=None,
        entitlements_file=None,
        icon=ICON,
    )
    coll = COLLECT(
        exe,
        a.binaries,
        a.datas,
        strip=False,
        upx=False,
        name="pyALDIC",
    )
    app = BUNDLE(
        coll,
        name="pyALDIC.app",
        icon=ICON,
        bundle_identifier="io.github.zachtong.pyaldic",
        version=VERSION,
        info_plist={
            "CFBundleName": "pyALDIC",
            "CFBundleDisplayName": "pyALDIC",
            "CFBundleShortVersionString": VERSION,
            "CFBundleVersion": VERSION,
            # The floor is set by the wheels the build collects, not by Qt:
            # numpy and scipy's arm64 wheels for macOS 14 link Accelerate's
            # newer interfaces, so the app would start on 13 and then fail to
            # import numpy. Say so up front instead.
            "LSMinimumSystemVersion": "14.0",
            "LSApplicationCategoryType": "public.app-category.education",
            "NSHighResolutionCapable": True,
            "NSHumanReadableCopyright": "BSD-3-Clause",
        },
    )

else:
    # UPX stays off: compressing Qt's DLLs is a dependable source of antivirus
    # false positives and load failures, and this bundle is already unsigned.
    exe = EXE(
        pyz,
        a.scripts,
        [],
        exclude_binaries=True,
        name="pyALDIC",
        debug=False,
        bootloader_ignore_signals=False,
        strip=False,
        upx=False,
        console=False,
        disable_windowed_traceback=False,
        icon=ICON,
        version=VERSION_FILE,
    )

    # A console twin sharing the same Analysis. Costs ~1 MB of bootloader and
    # buys a stdout: somewhere for CI to read a self-test result, and somewhere
    # for a user to see a traceback when the windowed build refuses to start.
    exe_console = EXE(
        pyz,
        a.scripts,
        [],
        exclude_binaries=True,
        name="pyALDIC-console",
        debug=False,
        bootloader_ignore_signals=False,
        strip=False,
        upx=False,
        console=True,
        disable_windowed_traceback=False,
        icon=ICON,
        version=VERSION_FILE,
    )

    coll = COLLECT(
        exe,
        exe_console,
        a.binaries,
        a.datas,
        strip=False,
        upx=False,
        upx_exclude=[],
        name="pyALDIC",
    )
